# Generated by Django 4.1.6 on 2023-04-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
